### ISSUE TITLE
Typos in book content: makePizza parameter, array.pop() mutation, and BST node values

### ISSUE THREAD

**Issue by mdribera** [amejiarosario/dsa.js-data-structures-algorithms-javascript#38]
Hi, I found a few errors in the book! I'll put up an accompanying PR with fixes.

<img width="546" alt="Screen Shot 2020-02-11 at 12 21 46 PM" src="https://user-images.githubusercontent.com/2905864/74274758-43a8bc00-4cd8-11ea-88c5-eb5933eaddfb.png">
<img width="544" alt="Screen Shot 2020-02-11 at 12 22 02 PM" src="https://user-images.githubusercontent.com/2905864/74274767-473c4300-4cd8-11ea-94f5-41b8f3350ade.png">
<img width="548" alt="Screen Shot 2020-02-11 at 12 27 15 PM" src="https://user-images.githubusercontent.com/2905864/74274774-4acfca00-4cd8-11ea-9444-7e98afb6d7ac.png">

**Comment by amejiarosario** [comment]
Thanks, Mark, for reporting these! I'll accept the PRs when you have them ready

**Comment by mdribera** [comment]
You're welcome! Thanks for the excellent content.
